# Generated by Django 3.0.6 on 2020-05-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item sold'), ('RESTOCKING', 'Item restocking in few days')], default='Sold', max_length=20),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item sold'), ('RESTOCKING', 'Item restocking in few days')], default='Sold', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item sold'), ('RESTOCKING', 'Item restocking in few days')], default='Sold', max_length=20),
        ),
    ]
